language: python
python: 3.6
branches:
  only:
  - master
before_install:
  - pip install pipenv
  - pipenv install
script:
  - pipenv run mkdocs build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: site
  target-branch: gh-pages
  on:
    branch: master