site_name: 建造以學習 | 在電梯裡遇見雙胞胎
site_url: https://imsardine.github.io/dev-notes
repo_url: https://github.com/imsardine/dev-notes
edit_uri: blob/source/docs/
repo_name: imsardine/dev-notes
theme: cinder
extra_css: ['cinder_extra.css']
dev_addr: 0.0.0.0:8000
markdown_extensions:
  - toc:
      permalink: ' #'
  - attr_list
  - smarty
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - pymdownx.arithmatex
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML
nav:
  - README.md
